<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RuntimeIdentifiers>win;linux</RuntimeIdentifiers>
    <GameVersion Condition="'$(GameVersion)' == ''">1.6</GameVersion>
    <CoreSKPatchRoot>$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)\..\..'))</CoreSKPatchRoot>
    <RimWorldRoot>$([System.IO.Path]::GetFullPath('$(CoreSKPatchRoot)\..\..'))</RimWorldRoot>
    <SteamAppsRoot>$([System.IO.Path]::GetFullPath('$(CoreSKPatchRoot)\..\..\..\..'))</SteamAppsRoot>
    <SOS2Root Condition="'$(SOS2Root)' == ''">$(SteamAppsRoot)\workshop\content\294100\1909914131</SOS2Root>
    <RimatomicsRoot Condition="'$(RimatomicsRoot)' == ''">$(RimWorldRoot)\Mods\Rimatomics_SK</RimatomicsRoot>
    <MineralsRoot Condition="'$(MineralsRoot)' == ''">$(RimWorldRoot)\Mods\Minerals</MineralsRoot>
    <OutputPath>$(CoreSKPatchRoot)\v$(GameVersion)\AssembliesCompat</OutputPath>
    <LangVersion>preview</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>SOS2Compat</AssemblyTitle>
    <Product>SOS2Compat</Product>
    <Copyright>Copyright ©  2023</Copyright>
    <Deterministic>true</Deterministic>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Publicize Include="ShipsHaveInsides;Assembly-CSharp" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Replacement\" />
    <Compile Remove="Projectile\Projectile_ExplosiveShipCombatKinetic.cs" Condition="'$(GameVersion)' != '1.6'" />
    <Compile Remove="Replacement\CompBecomeBuilding.cs" />
    <Compile Remove="Replacement\CompBecomePawn.cs" />
    <Compile Remove="Replacement\CompProperties_BecomeBuilding.cs" />
    <Compile Remove="Replacement\CompProperties_BecomePawn.cs" />
    <Compile Remove="Harmony.cs" Condition="'$(GameVersion)' == '1.6'" />
    <Compile Remove="Comp\CompShuttleStuff.cs" Condition="'$(GameVersion)' == '1.6'" />
    <Compile Remove="Rimatomics\**" Condition="'$(GameVersion)' != '1.6'" />
    <Compile Remove="Heat\**" Condition="'$(GameVersion)' != '1.6'" />
    <Compile Remove="Combat\**" Condition="'$(GameVersion)' != '1.6'" />
    <Compile Remove="Ocean\**" Condition="'$(GameVersion)' != '1.6'" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ShipsHaveInsides">
      <HintPath>$(SOS2Root)\$(GameVersion)\Assemblies\ShipsHaveInsides.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Minerals">
      <HintPath>$(MineralsRoot)\Assemblies\Minerals.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Rimatomics" Condition="'$(GameVersion)' == '1.6'">
      <HintPath>$(RimatomicsRoot)\Assemblies\Rimatomics.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Core_SK_Patch">
      <HintPath>$(CoreSKPatchRoot)\v$(GameVersion)\Assemblies\Core_SK_Patch.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <PackageReference Include="Krafs.Publicizer" Version="2.2.1" />
    <PackageReference Include="Krafs.Rimworld.Ref" Version="$(GameVersion).*" />
    <PackageReference Include="Lib.Harmony" Version="2.3.*" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
