<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>preview</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Version Condition="'$(Version)' == ''">1.6</Version>
    <AssemblyName>Core_SK_Patch.RimThemesCharacterEditorCompat</AssemblyName>
    <OutputPath>..\..\v$(Version)\Assemblies\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Deterministic>true</Deterministic>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="$(Version).*" />
    <PackageReference Include="Lib.Harmony" Version="2.3.*" ExcludeAssets="runtime" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Patches\RimThemesCharacterEditorWindowFix.cs"
             Link="RimThemesCharacterEditorWindowFix.cs" />
  </ItemGroup>
</Project>
